service: poc-ia

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  deploymentMethod: direct
  timeout: 30
  iamRoleStatements: 
    - Effect: "Allow"        
      Action:
        - bedrock:InvokeModel      
        - transcribe:StartTranscriptionJob       
        - transcribe:GetTranscriptionJob
        - polly:StartSpeechSynthesisTask       
        - s3:GetObject      
        - s3:PutObject       
      Resource: 
        - "*"
functions:
  process-audio-description:
      handler: main.handler
      events:
        - http:
            path: process-audio-description
            method: post